last_change = 2026-09-10T06:55:51.740444Z
addr = 0xa35620
size = 0x112
name = "CBaseEntity_GetChangeAccessorPathInfo_1"

[header]
name = "CBaseEntity_GetChangeAccessorPathInfo_1"
addr = 0xa35620

[header.args]
