last_change = 2026-09-10T18:39:12.764097Z
addr = 0xaa5010
size = 0x615
name = "CNetworkTransmitComponent_StateChanged"
type = "void"

[header]
name = "CNetworkTransmitComponent_StateChanged"
addr = 0xaa5010
type = "void"

[header.args]
