last_change = 2026-09-11T03:35:17.237738Z
addr = 0xacd610
size = 0x12b
name = "CSource2Server_GetMatchmakingGameData"

[header]
name = "CSource2Server_GetMatchmakingGameData"
addr = 0xacd610

[header.args]
