last_change = 2026-09-10T06:55:51.740460Z
addr = 0xacd610
size = 0x12b
name = "CSource2Server_GetMatchmakingGameData"

[header]
name = "CSource2Server_GetMatchmakingGameData"
addr = 0xacd610

[header.args]
