last_change = 2026-09-11T03:35:17.237765Z
addr = 0xaee320
size = 0xc1c
name = "CCSPlayerPawn_ProcessSuicideAsKillReward"

[header]
name = "CCSPlayerPawn_ProcessSuicideAsKillReward"
addr = 0xaee320

[header.args]
