last_change = 2026-09-11T03:35:17.237751Z
addr = 0xae9110
size = 0x25e
name = "CCSPlayerPawn_CreatePlayerPawnServices"

[header]
name = "CCSPlayerPawn_CreatePlayerPawnServices"
addr = 0xae9110

[header.args]
