last_change = 2026-09-11T03:35:17.237811Z
addr = 0xb0ebe0
size = 0x676
name = "CDedicatedServerWorkshopManager_SwitchToWorkshopMapGroup"

[header]
name = "CDedicatedServerWorkshopManager_SwitchToWorkshopMapGroup"
addr = 0xb0ebe0

[header.args]
