last_change = 2026-09-10T06:55:51.740501Z
addr = 0xb0ebe0
size = 0x676
name = "CDedicatedServerWorkshopManager_SwitchToWorkshopMapGroup"

[header]
name = "CDedicatedServerWorkshopManager_SwitchToWorkshopMapGroup"
addr = 0xb0ebe0

[header.args]
