last_change = 2026-09-10T18:39:02.340108Z
addr = 0xb17490
size = 0xd3
name = "ClientPutInServer"
type = "long long"

[header]
name = "ClientPutInServer"
addr = 0xb17490
type = "long long"

[header.args]
