last_change = 2026-09-10T18:39:02.340125Z
addr = 0xb3b850
size = 0x2bd
name = "ScriptBinding_CBaseModelEntity_SetModel"
type = "long long"

[header]
name = "ScriptBinding_CBaseModelEntity_SetModel"
addr = 0xb3b850
type = "long long"

[header.args]
