last_change = 2026-09-11T03:35:17.237835Z
addr = 0xb3b850
size = 0x2bd
name = "ScriptBinding_CBaseModelEntity_SetModel"

[header]
name = "ScriptBinding_CBaseModelEntity_SetModel"
addr = 0xb3b850

[header.args]
