last_change = 2026-09-11T03:35:17.237829Z
addr = 0xb38440
size = 0x2ad
name = "ScriptBinding_Entity_SetEntityName"

[header]
name = "ScriptBinding_Entity_SetEntityName"
addr = 0xb38440

[header.args]
