last_change = 2026-09-11T03:35:17.237847Z
addr = 0xb49df0
size = 0x28d
name = "CCSPlayerPawnBase_CheckForIdleInternal"

[header]
name = "CCSPlayerPawnBase_CheckForIdleInternal"
addr = 0xb49df0

[header.args]
