last_change = 2026-09-10T18:39:02.340222Z
addr = 0xc235b0
size = 0x87a
name = "CCSBotManager_BotPlaceCommand"
type = "long long"

[header]
name = "CCSBotManager_BotPlaceCommand"
addr = 0xc235b0
type = "long long"

[header.args]
