last_change = 2026-09-11T03:35:17.238028Z
addr = 0xd3af10
size = 0x287
name = "CBaseEntity_ModifyOrAppendCriteria"

[header]
name = "CBaseEntity_ModifyOrAppendCriteria"
addr = 0xd3af10

[header.args]
