last_change = 2026-09-10T18:39:02.340367Z
addr = 0xd79700
size = 0x111
name = "CBaseEntity_Teleport"
type = "long long"

[header]
name = "CBaseEntity_Teleport"
addr = 0xd79700
type = "long long"

[header.args]
