last_change = 2026-09-11T03:35:17.238174Z
addr = 0xee7290
size = 0xc1
name = "IGameSystem_LoopPreShutdownAllSystems"

[header]
name = "IGameSystem_LoopPreShutdownAllSystems"
addr = 0xee7290

[header.args]
