last_change = 2026-09-11T03:35:17.238251Z
addr = 0xf4ed00
size = 0x3f3
name = "CSpawnGroupMgrGameSystem_DumpSpawnGroups"

[header]
name = "CSpawnGroupMgrGameSystem_DumpSpawnGroups"
addr = 0xf4ed00

[header.args]
