last_change = 2026-09-10T18:39:02.340486Z
addr = 0xf46750
size = 0x2af
name = "CSpawnGroupMgrGameSystem_SpawnGroupShutdown"
type = "double"

[header]
name = "CSpawnGroupMgrGameSystem_SpawnGroupShutdown"
addr = 0xf46750
type = "double"

[header.args]
