last_change = 2026-09-11T03:35:17.238240Z
addr = 0xf46750
size = 0x2af
name = "CSpawnGroupMgrGameSystem_SpawnGroupShutdown"

[header]
name = "CSpawnGroupMgrGameSystem_SpawnGroupShutdown"
addr = 0xf46750

[header.args]
