last_change = 2026-09-11T03:35:17.238229Z
addr = 0xf43090
size = 0x268
name = "CSpawnGroupMgrGameSystem_SetActiveSpawnGroup"

[header]
name = "CSpawnGroupMgrGameSystem_SetActiveSpawnGroup"
addr = 0xf43090

[header.args]
