last_change = 2026-09-10T18:39:02.340508Z
addr = 0xf5a270
size = 0x410
name = "CSpawnGroupMgrGameSystem_SpawnGroupSpawnEntities"
type = "unsigned int *"

[header]
name = "CSpawnGroupMgrGameSystem_SpawnGroupSpawnEntities"
addr = 0xf5a270
type = "unsigned int *"

[header.args]
