last_change = 2026-09-11T03:35:17.238262Z
addr = 0xf5a270
size = 0x410
name = "CSpawnGroupMgrGameSystem_SpawnGroupSpawnEntities"

[header]
name = "CSpawnGroupMgrGameSystem_SpawnGroupSpawnEntities"
addr = 0xf5a270

[header.args]
