last_change = 2026-09-11T03:35:17.238267Z
addr = 0xf72760
size = 0x311
name = "CSpawnGroupMgrGameSystem_UnloadSpawnGroup"

[header]
name = "CSpawnGroupMgrGameSystem_UnloadSpawnGroup"
addr = 0xf72760

[header.args]
