last_change = 2026-09-11T03:35:17.238278Z
addr = 0xf86800
size = 0x5c0
name = "CSpawnGroupMgrGameSystem_ReleaseSpawnGroup"

[header]
name = "CSpawnGroupMgrGameSystem_ReleaseSpawnGroup"
addr = 0xf86800

[header.args]
