last_change = 2026-09-10T18:39:02.340519Z
addr = 0xf85680
size = 0x6e0
name = "CSpawnGroupMgrGameSystem_AllocateSpawnGroup"
type = "long long"

[header]
name = "CSpawnGroupMgrGameSystem_AllocateSpawnGroup"
addr = 0xf85680
type = "long long"

[header.args]
