last_change = 2026-09-10T06:55:51.740693Z
addr = 0xf85680
size = 0x6e0
name = "CSpawnGroupMgrGameSystem_AllocateSpawnGroup"

[header]
name = "CSpawnGroupMgrGameSystem_AllocateSpawnGroup"
addr = 0xf85680

[header.args]
