last_change = 2026-09-11T03:35:17.238272Z
addr = 0xf85680
size = 0x6e0
name = "CSpawnGroupMgrGameSystem_AllocateSpawnGroup"

[header]
name = "CSpawnGroupMgrGameSystem_AllocateSpawnGroup"
addr = 0xf85680

[header.args]
