last_change = 2026-09-11T03:35:32.505206Z
addr = 0x134c740
size = 0x602
name = "PolymorphicHelper_t__SetPolymorphicPointer"

[header]
name = "PolymorphicHelper_t__SetPolymorphicPointer"
addr = 0x134c740

[header.args]
