last_change = 2026-09-10T18:39:02.340801Z
addr = 0x135e020
size = 0x55a
name = "CHostage_Follow"
type = "long long"

[header]
name = "CHostage_Follow"
addr = 0x135e020
type = "long long"

[header.args]
