last_change = 2026-09-10T18:39:02.340818Z
addr = 0x13d5330
size = 0xea8
name = "CCSGameRules_GoToIntermission"
type = "long long"

[header]
name = "CCSGameRules_GoToIntermission"
addr = 0x13d5330
type = "long long"

[header.args]
