last_change = 2026-09-10T18:39:18.028823Z
addr = 0x1437790
size = 0x116
name = "SmokeVolume_BuildSmokeSimulation_Initialize"
type = "void"

[header]
name = "SmokeVolume_BuildSmokeSimulation_Initialize"
addr = 0x1437790
type = "void"

[header.args]
