last_change = 2026-09-10T18:39:02.340860Z
addr = 0x147a8d0
size = 0x2ea
name = "CBasePlayerWeapon_Shoot_Secondary"
type = "long long"

[header]
name = "CBasePlayerWeapon_Shoot_Secondary"
addr = 0x147a8d0
type = "long long"

[header.args]
