last_change = 2026-09-11T03:35:17.238623Z
addr = 0x14978f0
size = 0x18e
name = "CCSWeaponBase_ItemPostFrame_ProcessReloadAction"

[header]
name = "CCSWeaponBase_ItemPostFrame_ProcessReloadAction"
addr = 0x14978f0

[header.args]
