last_change = 2026-09-11T03:35:17.238635Z
addr = 0x150c230
size = 0x45
name = "CCSPlayerController_HandleCommandDrop"

[header]
name = "CCSPlayerController_HandleCommandDrop"
addr = 0x150c230

[header.args]
