last_change = 2026-09-11T03:35:33.119847Z
addr = 0x150cad0
size = 0xaf
name = "CCSPlayerController_GetThinkFunction"
type = "long long"

[header]
name = "CCSPlayerController_GetThinkFunction"
addr = 0x150cad0
type = "long long"

[header.args]
