last_change = 2026-09-10T06:56:08.134276Z
addr = 0x150cad0
size = 0xaf
name = "CCSPlayerController_GetThinkFunction"
type = "long long"

[header]
name = "CCSPlayerController_GetThinkFunction"
addr = 0x150cad0
type = "long long"

[header.args]
