last_change = 2026-09-11T03:35:17.238690Z
addr = 0x155e230
size = 0xee8
name = "CBasePlayerController_HandleCommand_JoinTeam"

[header]
name = "CBasePlayerController_HandleCommand_JoinTeam"
addr = 0x155e230

[header.args]
