last_change = 2026-09-11T03:35:17.238716Z
addr = 0x1566a80
size = 0x1c
name = "CCSPlayer_ItemServices_GiveNamedItemBool"

[header]
name = "CCSPlayer_ItemServices_GiveNamedItemBool"
addr = 0x1566a80

[header.args]
