last_change = 2026-09-10T18:39:02.340972Z
addr = 0x1577f10
size = 0xb59
name = "CCSPlayer_UseServices_BumpWeapon"
type = "long long"

[header]
name = "CCSPlayer_UseServices_BumpWeapon"
addr = 0x1577f10
type = "long long"

[header.args]
