last_change = 2026-09-11T03:35:17.238760Z
addr = 0x1587d40
size = 0x8fa
name = "CCSPlayer_ItemServices_GiveDefaultItems"

[header]
name = "CCSPlayer_ItemServices_GiveDefaultItems"
addr = 0x1587d40

[header.args]
