last_change = 2026-09-11T03:35:17.238782Z
addr = 0x15b3230
size = 0x17b
name = "CCSPlayer_ItemServices_RemoveWeapons"

[header]
name = "CCSPlayer_ItemServices_RemoveWeapons"
addr = 0x15b3230

[header.args]
