last_change = 2026-09-11T03:35:17.238777Z
addr = 0x15b30f0
size = 0x131
name = "CCSPlayer_ItemServices_DropActivePlayerWeapon"

[header]
name = "CCSPlayer_ItemServices_DropActivePlayerWeapon"
addr = 0x15b30f0

[header.args]
