last_change = 2026-09-10T06:55:51.740923Z
addr = 0x15b30f0
size = 0x131
name = "CCSPlayer_ItemServices_DropActivePlayerWeapon"

[header]
name = "CCSPlayer_ItemServices_DropActivePlayerWeapon"
addr = 0x15b30f0

[header.args]
