last_change = 2026-09-10T18:39:19.211159Z
addr = 0x15b30f0
size = 0x131
name = "CCSPlayer_ItemServices_DropActivePlayerWeapon"
type = "long long"

[header]
name = "CCSPlayer_ItemServices_DropActivePlayerWeapon"
addr = 0x15b30f0
type = "long long"

[header.args]
