last_change = 2026-09-10T18:39:02.341035Z
addr = 0x15c2120
size = 0x11
name = "CBasePlayerPawn_RemovePlayerItem"
type = "long long"

[header]
name = "CBasePlayerPawn_RemovePlayerItem"
addr = 0x15c2120
type = "long long"

[header.args]
