last_change = 2026-09-11T03:35:17.238803Z
addr = 0x15c2290
size = 0x206
name = "CCSPlayer_WeaponServices_SelectItem"

[header]
name = "CCSPlayer_WeaponServices_SelectItem"
addr = 0x15c2290

[header.args]
