last_change = 2026-09-10T18:39:02.341050Z
addr = 0x15cde70
size = 0x2fb
name = "CCSPlayer_WeaponServices_DropWeapon"
type = "void"

[header]
name = "CCSPlayer_WeaponServices_DropWeapon"
addr = 0x15cde70
type = "void"

[header.args]
