last_change = 2026-09-10T06:55:51.740942Z
addr = 0x15d1e00
size = 0x26f
name = "CCSPlayer_WeaponServices_EquipWeapon"

[header]
name = "CCSPlayer_WeaponServices_EquipWeapon"
addr = 0x15d1e00

[header.args]
