last_change = 2026-09-10T06:55:51.740944Z
addr = 0x15d2070
size = 0xaa5
name = "CCSPlayer_WeaponServices_PickupItem"

[header]
name = "CCSPlayer_WeaponServices_PickupItem"
addr = 0x15d2070

[header.args]
