last_change = 2026-09-10T18:39:19.500876Z
addr = 0x15d1e00
size = 0x26f
name = "CCSPlayer_WeaponServices_EquipWeapon"
type = "long long"

[header]
name = "CCSPlayer_WeaponServices_EquipWeapon"
addr = 0x15d1e00
type = "long long"

[header.args]
