last_change = 2026-09-11T03:35:17.238818Z
addr = 0x15d1e00
size = 0x26f
name = "CCSPlayer_WeaponServices_EquipWeapon"

[header]
name = "CCSPlayer_WeaponServices_EquipWeapon"
addr = 0x15d1e00

[header.args]
