last_change = 2026-09-11T03:35:17.238839Z
addr = 0x15fa270
size = 0x83
name = "CBasePlayerPawn_PrePhysicsSimulate"

[header]
name = "CBasePlayerPawn_PrePhysicsSimulate"
addr = 0x15fa270

[header.args]
