last_change = 2026-09-11T03:35:17.238855Z
addr = 0x160b320
size = 0x1f
name = "CBaseAnimGraph_GetAnimationController"

[header]
name = "CBaseAnimGraph_GetAnimationController"
addr = 0x160b320

[header.args]
