last_change = 2026-09-10T06:55:51.740958Z
addr = 0x160b320
size = 0x1f
name = "CBaseAnimGraph_GetAnimationController"

[header]
name = "CBaseAnimGraph_GetAnimationController"
addr = 0x160b320

[header.args]
