last_change = 2026-09-11T03:35:17.238925Z
addr = 0x16163e0
size = 0x58
name = "CBasePlayerController_IsFakeClient"

[header]
name = "CBasePlayerController_IsFakeClient"
addr = 0x16163e0

[header.args]
