last_change = 2026-09-10T06:55:51.740986Z
addr = 0x16163e0
size = 0x58
name = "CBasePlayerController_IsFakeClient"

[header]
name = "CBasePlayerController_IsFakeClient"
addr = 0x16163e0

[header.args]
