last_change = 2026-09-10T18:39:02.341195Z
addr = 0x1617690
size = 0x1dc
name = "CBasePlayerController_SimulateUserCommands"
type = "long long"

[header]
name = "CBasePlayerController_SimulateUserCommands"
addr = 0x1617690
type = "long long"

[header.args]
