last_change = 2026-09-10T18:39:02.341207Z
addr = 0x16199b0
size = 0x1ea
name = "CBasePlayerPawn_GetEyePosition"
type = "__m128"

[header]
name = "CBasePlayerPawn_GetEyePosition"
addr = 0x16199b0
type = "__m128"

[header.args]
