last_change = 2026-09-10T06:55:51.740963Z
addr = 0x1612530
size = 0x42
name = "CBaseModelEntity_Script_SetModelScale"

[header]
name = "CBaseModelEntity_Script_SetModelScale"
addr = 0x1612530

[header.args]
