last_change = 2026-09-11T03:35:17.238955Z
addr = 0x1625200
size = 0x253
name = "CBasePlayerController_SetPlayerName"

[header]
name = "CBasePlayerController_SetPlayerName"
addr = 0x1625200

[header.args]
