last_change = 2026-09-10T06:55:51.741009Z
addr = 0x165bd70
size = 0x583
name = "CBasePlayerController_ProcessUsercmds"

[header]
name = "CBasePlayerController_ProcessUsercmds"
addr = 0x165bd70

[header.args]
