last_change = 2026-09-11T03:35:17.238987Z
addr = 0x165dbe0
size = 0x3e3
name = "CBasePlayerController_ClientSettingsChanged"

[header]
name = "CBasePlayerController_ClientSettingsChanged"
addr = 0x165dbe0

[header.args]
