last_change = 2026-09-11T03:35:17.238982Z
addr = 0x165c300
size = 0x669
name = "CBasePlayerController_SetConnectedState"

[header]
name = "CBasePlayerController_SetConnectedState"
addr = 0x165c300

[header.args]
