last_change = 2026-09-10T06:55:51.741012Z
addr = 0x165c300
size = 0x669
name = "CBasePlayerController_SetConnectedState"

[header]
name = "CBasePlayerController_SetConnectedState"
addr = 0x165c300

[header.args]
