last_change = 2026-09-10T18:39:02.341282Z
addr = 0x1669760
size = 0x83
name = "CBaseFilter_InputTestActivator"
type = "long long"

[header]
name = "CBaseFilter_InputTestActivator"
addr = 0x1669760
type = "long long"

[header.args]
