last_change = 2026-09-10T18:39:20.952995Z
addr = 0x16bda10
size = 0xa7
name = "CGameEntitySystem_OnAddEntity"
type = "void"

[header]
name = "CGameEntitySystem_OnAddEntity"
addr = 0x16bda10
type = "void"

[header.args]
