last_change = 2026-09-10T18:39:02.341295Z
addr = 0x16b5e40
size = 0x41
name = "CSaveRestoreBlockSet_PreRestore"
type = "long long"

[header]
name = "CSaveRestoreBlockSet_PreRestore"
addr = 0x16b5e40
type = "long long"

[header.args]
