last_change = 2026-09-11T03:35:17.239035Z
addr = 0x16cff90
size = 0x382
name = "CEntitySaveRestoreBlockHandler_ReadRestoreHeaders"

[header]
name = "CEntitySaveRestoreBlockHandler_ReadRestoreHeaders"
addr = 0x16cff90

[header.args]
