last_change = 2026-09-11T03:35:17.239041Z
addr = 0x16d1f90
size = 0x270
name = "CGameEntitySystem_FindEntityProcedural"

[header]
name = "CGameEntitySystem_FindEntityProcedural"
addr = 0x16d1f90

[header.args]
