last_change = 2026-09-10T18:39:21.060055Z
addr = 0x16db050
size = 0x375
name = "CEntitySaveRestoreBlockHandler_SaveInternal"
type = "long long"

[header]
name = "CEntitySaveRestoreBlockHandler_SaveInternal"
addr = 0x16db050
type = "long long"

[header.args]
