last_change = 2026-09-11T03:35:17.239061Z
addr = 0x16db800
size = 0x1ba
name = "CEntitySaveRestoreBlockHandler_DoRestoreEntity"

[header]
name = "CEntitySaveRestoreBlockHandler_DoRestoreEntity"
addr = 0x16db800

[header.args]
