last_change = 2026-09-11T03:35:17.239051Z
addr = 0x16db3e0
size = 0x212
name = "CEntitySaveRestoreBlockHandler_SaveInitEntities"

[header]
name = "CEntitySaveRestoreBlockHandler_SaveInitEntities"
addr = 0x16db3e0

[header.args]
