last_change = 2026-09-11T03:35:17.239076Z
addr = 0x16dd2c0
size = 0xd26
name = "CEntitySaveRestoreBlockHandler_WriteSaveHeaders"

[header]
name = "CEntitySaveRestoreBlockHandler_WriteSaveHeaders"
addr = 0x16dd2c0

[header.args]
