last_change = 2026-09-11T03:35:17.239056Z
addr = 0x16db600
size = 0x1fe
name = "CEntitySaveRestoreBlockHandler_PreSave"

[header]
name = "CEntitySaveRestoreBlockHandler_PreSave"
addr = 0x16db600

[header.args]
