last_change = 2026-09-11T03:35:17.239046Z
addr = 0x16db050
size = 0x375
name = "CEntitySaveRestoreBlockHandler_SaveInternal"

[header]
name = "CEntitySaveRestoreBlockHandler_SaveInternal"
addr = 0x16db050

[header.args]
