last_change = 2026-09-10T18:39:02.341448Z
addr = 0x16eb600
size = 0x75
name = "CGameSceneNode_PreInstanceSpawn"
type = "long long"

[header]
name = "CGameSceneNode_PreInstanceSpawn"
addr = 0x16eb600
type = "long long"

[header.args]
