last_change = 2026-09-10T18:39:02.341432Z
addr = 0x16e43c0
size = 0x6
name = "CGameEventManager_Shutdown"
type = "long long"

[header]
name = "CGameEventManager_Shutdown"
addr = 0x16e43c0
type = "long long"

[header.args]
