last_change = 2026-09-11T03:35:17.239158Z
addr = 0x16ec380
size = 0xd9
name = "CGameSceneNode_UpdateEntityForHierarchyChange"

[header]
name = "CGameSceneNode_UpdateEntityForHierarchyChange"
addr = 0x16ec380

[header.args]
