last_change = 2026-09-10T18:39:02.341390Z
addr = 0x16e0430
size = 0x28
name = "CGameEntitySystem_FindEntityByClassName"
type = "long long"

[header]
name = "CGameEntitySystem_FindEntityByClassName"
addr = 0x16e0430
type = "long long"

[header.args]
