last_change = 2026-09-10T18:39:02.341458Z
addr = 0x16ec460
size = 0x209
name = "CGameSceneNode_PostDataUpdate"
type = "long long"

[header]
name = "CGameSceneNode_PostDataUpdate"
addr = 0x16ec460
type = "long long"

[header.args]
