last_change = 2026-09-10T18:39:02.341470Z
addr = 0x17074e0
size = 0x2dd
name = "CLoadingSpawnGroup_CreateEntityToSpawn"
type = "const __m128i *"

[header]
name = "CLoadingSpawnGroup_CreateEntityToSpawn"
addr = 0x17074e0
type = "const __m128i *"

[header.args]
