last_change = 2026-09-11T03:35:17.239175Z
addr = 0x17074e0
size = 0x2dd
name = "CLoadingSpawnGroup_CreateEntityToSpawn"

[header]
name = "CLoadingSpawnGroup_CreateEntityToSpawn"
addr = 0x17074e0

[header.args]
