last_change = 2026-09-11T03:35:17.239186Z
addr = 0x1719680
size = 0xbc0
name = "CEntitySaveRestoreBlockHandler_Restore"

[header]
name = "CEntitySaveRestoreBlockHandler_Restore"
addr = 0x1719680

[header.args]
