last_change = 2026-09-10T18:39:02.341480Z
addr = 0x1719680
size = 0xbc0
name = "CEntitySaveRestoreBlockHandler_Restore"
type = "long long"

[header]
name = "CEntitySaveRestoreBlockHandler_Restore"
addr = 0x1719680
type = "long long"

[header.args]
