last_change = 2026-09-11T03:35:17.239207Z
addr = 0x1738c60
size = 0xbc
name = "CEntity2NetworkClasses_ServerClass_InitEntity2NetworkClasses"

[header]
name = "CEntity2NetworkClasses_ServerClass_InitEntity2NetworkClasses"
addr = 0x1738c60

[header.args]
