last_change = 2026-09-10T18:39:22.123970Z
addr = 0x1738c60
size = 0xbc
name = "CEntity2NetworkClasses_ServerClass_InitEntity2NetworkClasses"
type = "long long"

[header]
name = "CEntity2NetworkClasses_ServerClass_InitEntity2NetworkClasses"
addr = 0x1738c60
type = "long long"

[header.args]
