last_change = 2026-09-11T03:35:17.239197Z
addr = 0x17314c0
size = 0xa4c
name = "CEntity2SaveRestore_StreamEntitiesFromFile"

[header]
name = "CEntity2SaveRestore_StreamEntitiesFromFile"
addr = 0x17314c0

[header.args]
