last_change = 2026-09-10T18:39:02.341549Z
addr = 0x1744ce0
size = 0xbb
name = "CLoopModeGame_OnFrameBoundary"
type = "long long"

[header]
name = "CLoopModeGame_OnFrameBoundary"
addr = 0x1744ce0
type = "long long"

[header.args]
