last_change = 2026-09-10T18:39:02.341534Z
addr = 0x1744aa0
size = 0xbb
name = "CLoopModeGame_OnServerAdvanceTick"
type = "long long"

[header]
name = "CLoopModeGame_OnServerAdvanceTick"
addr = 0x1744aa0
type = "long long"

[header.args]
