last_change = 2026-09-10T18:39:02.341601Z
addr = 0x174be20
size = 0xa9
name = "CLoopModeGame_ShutdownServer"
type = "unsigned long long *"

[header]
name = "CLoopModeGame_ShutdownServer"
addr = 0x174be20
type = "unsigned long long *"

[header.args]
