last_change = 2026-09-11T03:35:17.239249Z
addr = 0x1744c20
size = 0xbb
name = "CLoopModeGame_OnServerPostAdvanceTick"

[header]
name = "CLoopModeGame_OnServerPostAdvanceTick"
addr = 0x1744c20

[header.args]
