last_change = 2026-09-11T03:35:17.239234Z
addr = 0x1744a40
size = 0x57
name = "CLoopModeGame_AddViewsToSceneSystem"

[header]
name = "CLoopModeGame_AddViewsToSceneSystem"
addr = 0x1744a40

[header.args]
