last_change = 2026-09-10T18:39:02.341617Z
addr = 0x17543a0
size = 0x2d7
name = "CLoopModeGame_OnServerBeginAsyncPostTickWork"
type = "long long (__fastcall *)()"

[header]
name = "CLoopModeGame_OnServerBeginAsyncPostTickWork"
addr = 0x17543a0
type = "long long (__fastcall *)()"

[header.args]
