last_change = 2026-09-10T18:39:22.998688Z
addr = 0x1755070
size = 0x6f
name = "CLoopModeFactory_CLoopModeGame_Shutdown"

[header]
name = "CLoopModeFactory_CLoopModeGame_Shutdown"
addr = 0x1755070

[header.args]
