last_change = 2026-09-10T18:39:23.139850Z
addr = 0x175dc50
size = 0x16bd
name = "CLoopModeGame_LoopInitInternal"
type = "long long"

[header]
name = "CLoopModeGame_LoopInitInternal"
addr = 0x175dc50
type = "long long"

[header.args]
