last_change = 2026-09-10T18:39:02.341674Z
addr = 0x1768af0
size = 0x13
name = "CLoopModeFactory_CLoopModeGame_Init"
type = "long long"

[header]
name = "CLoopModeFactory_CLoopModeGame_Init"
addr = 0x1768af0
type = "long long"

[header.args]
