last_change = 2026-09-11T03:35:17.239364Z
addr = 0x1768600
size = 0x416
name = "CLoopModeGame_RegisterEventMapInternal"

[header]
name = "CLoopModeGame_RegisterEventMapInternal"
addr = 0x1768600

[header.args]
