last_change = 2026-09-11T03:35:17.239379Z
addr = 0x1768af0
size = 0x13
name = "CLoopModeFactory_CLoopModeGame_Init"

[header]
name = "CLoopModeFactory_CLoopModeGame_Init"
addr = 0x1768af0

[header.args]
