last_change = 2026-09-10T06:55:51.741179Z
addr = 0x1768600
size = 0x416
name = "CLoopModeGame_RegisterEventMapInternal"

[header]
name = "CLoopModeGame_RegisterEventMapInternal"
addr = 0x1768600

[header.args]
