last_change = 2026-09-11T03:35:17.239385Z
addr = 0x177a760
size = 0x699
name = "CPlayer_MovementServices_PlayWaterStepSound"

[header]
name = "CPlayer_MovementServices_PlayWaterStepSound"
addr = 0x177a760

[header.args]
