last_change = 2026-09-11T03:35:17.239396Z
addr = 0x1782500
size = 0x3d8
name = "CPlayer_MovementServices_ForceButtons"

[header]
name = "CPlayer_MovementServices_ForceButtons"
addr = 0x1782500

[header.args]
