last_change = 2026-09-10T18:39:23.559796Z
addr = 0x17bf520
size = 0x117
name = "UTIL_GetPlayerControllerForEntity"
type = "unsigned int *"

[header]
name = "UTIL_GetPlayerControllerForEntity"
addr = 0x17bf520
type = "unsigned int *"

[header.args]
