last_change = 2026-09-10T18:39:02.341822Z
addr = 0x180e8e0
size = 0x11c
name = "CBaseCombatCharacter_OnKilled"
type = "long long"

[header]
name = "CBaseCombatCharacter_OnKilled"
addr = 0x180e8e0
type = "long long"

[header.args]
