last_change = 2026-09-10T18:39:02.341790Z
addr = 0x180de10
size = 0x18a
name = "CBaseEntity_dtor"
type = "long long *"

[header]
name = "CBaseEntity_dtor"
addr = 0x180de10
type = "long long *"

[header.args]
