last_change = 2026-09-10T18:39:02.341924Z
addr = 0x181be30
size = 0x382
name = "CMomentaryRotButton_Use"
type = "void"

[header]
name = "CMomentaryRotButton_Use"
addr = 0x181be30
type = "void"

[header.args]
