last_change = 2026-09-10T18:39:02.341982Z
addr = 0x1859ad0
size = 0x129
name = "CBaseEntity_OnSetDormant"
type = "long long"

[header]
name = "CBaseEntity_OnSetDormant"
addr = 0x1859ad0
type = "long long"

[header.args]
