last_change = 2026-09-10T18:39:02.342008Z
addr = 0x189ee50
size = 0x67
name = "CEnvShake_Spawn"
type = "long long"

[header]
name = "CEnvShake_Spawn"
addr = 0x189ee50
type = "long long"

[header.args]
