last_change = 2026-09-11T03:35:17.239872Z
addr = 0x190a590
size = 0x12a
name = "CSource2Server_BroadcastServerFrameTime"

[header]
name = "CSource2Server_BroadcastServerFrameTime"
addr = 0x190a590

[header.args]
