last_change = 2026-09-11T03:35:17.239788Z
addr = 0x1907010
size = 0xbb
name = "CSource2Server_UpdateWhenNotInGame"

[header]
name = "CSource2Server_UpdateWhenNotInGame"
addr = 0x1907010

[header.args]
