last_change = 2026-09-10T06:55:51.741352Z
addr = 0x19076c0
size = 0x22
name = "CSource2GameClients_ClientSettingsChanged"

[header]
name = "CSource2GameClients_ClientSettingsChanged"
addr = 0x19076c0

[header.args]
