last_change = 2026-09-10T18:39:02.342040Z
addr = 0x1907010
size = 0xbb
name = "CSource2Server_UpdateWhenNotInGame"
type = "long long"

[header]
name = "CSource2Server_UpdateWhenNotInGame"
addr = 0x1907010
type = "long long"

[header.args]
