last_change = 2026-09-11T03:35:17.239878Z
addr = 0x190ad10
size = 0xd1
name = "CGameRulesGameSystem_OnGameShutdown"

[header]
name = "CGameRulesGameSystem_OnGameShutdown"
addr = 0x190ad10

[header.args]
