last_change = 2026-09-10T18:39:02.342132Z
addr = 0x190af00
size = 0x7a
name = "CGameRules_GetChatPrefix"
type = "const char *"

[header]
name = "CGameRules_GetChatPrefix"
addr = 0x190af00
type = "const char *"

[header.args]
