last_change = 2026-09-11T03:35:17.239857Z
addr = 0x1909980
size = 0x1b2
name = "CSource2GameClients_GetBugReportInfo"

[header]
name = "CSource2GameClients_GetBugReportInfo"
addr = 0x1909980

[header.args]
