last_change = 2026-09-11T03:35:17.239863Z
addr = 0x190a130
size = 0xa3
name = "CSource2GameEntities_ShouldClientReceiveStringTableUserData"

[header]
name = "CSource2GameEntities_ShouldClientReceiveStringTableUserData"
addr = 0x190a130

[header.args]
