last_change = 2026-09-10T18:39:02.342075Z
addr = 0x1908000
size = 0xef
name = "CSource2GameClients_ClientPutInServer"
type = "unsigned int *"

[header]
name = "CSource2GameClients_ClientPutInServer"
addr = 0x1908000
type = "unsigned int *"

[header.args]
