last_change = 2026-09-11T03:35:17.239831Z
addr = 0x19080f0
size = 0xa
name = "CSource2GameClients_ClientSetConVarUserInfoSet"

[header]
name = "CSource2GameClients_ClientSetConVarUserInfoSet"
addr = 0x19080f0

[header.args]
