last_change = 2026-09-10T18:39:02.342030Z
addr = 0x1906c90
size = 0xef
name = "CSource2Server_WriteSignonMessages"
type = "long long"

[header]
name = "CSource2Server_WriteSignonMessages"
addr = 0x1906c90
type = "long long"

[header.args]
