last_change = 2026-09-11T03:35:17.239826Z
addr = 0x1908000
size = 0xef
name = "CSource2GameClients_ClientPutInServer"

[header]
name = "CSource2GameClients_ClientPutInServer"
addr = 0x1908000

[header.args]
