last_change = 2026-09-10T18:39:02.342127Z
addr = 0x190ad10
size = 0xd1
name = "CGameRulesGameSystem_OnGameShutdown"
type = "void"

[header]
name = "CGameRulesGameSystem_OnGameShutdown"
addr = 0x190ad10
type = "void"

[header.args]
