last_change = 2026-09-11T03:35:17.239963Z
addr = 0x191ce60
size = 0x11f
name = "CSource2GameClients_ClientCommand"

[header]
name = "CSource2GameClients_ClientCommand"
addr = 0x191ce60

[header.args]
