last_change = 2026-09-10T18:39:02.342202Z
addr = 0x191c900
size = 0x55d
name = "CSource2Server_GetEntityReport"
type = "long long"

[header]
name = "CSource2Server_GetEntityReport"
addr = 0x191c900
type = "long long"

[header.args]
