last_change = 2026-09-10T18:39:02.342157Z
addr = 0x19113d0
size = 0x215
name = "CSource2GameClients_ClientSetupVisibility"
type = "long long"

[header]
name = "CSource2GameClients_ClientSetupVisibility"
addr = 0x19113d0
type = "long long"

[header.args]
