last_change = 2026-09-11T03:35:17.239916Z
addr = 0x19115f0
size = 0xbf
name = "CSource2Server_ServerConVarChanged"

[header]
name = "CSource2Server_ServerConVarChanged"
addr = 0x19115f0

[header.args]
