last_change = 2026-09-10T18:39:02.342187Z
addr = 0x1912eb0
size = 0x31d
name = "CSource2GameClients_ClientDisconnect"
type = "long long (__fastcall *)()"

[header]
name = "CSource2GameClients_ClientDisconnect"
addr = 0x1912eb0
type = "long long (__fastcall *)()"

[header.args]
