last_change = 2026-09-10T18:39:02.342172Z
addr = 0x1912890
size = 0xc0
name = "CSource2Server_OnHostNameChanged"
type = "unsigned long long *"

[header]
name = "CSource2Server_OnHostNameChanged"
addr = 0x1912890
type = "unsigned long long *"

[header.args]
