last_change = 2026-09-11T03:35:17.239911Z
addr = 0x19113d0
size = 0x215
name = "CSource2GameClients_ClientSetupVisibility"

[header]
name = "CSource2GameClients_ClientSetupVisibility"
addr = 0x19113d0

[header.args]
