last_change = 2026-09-11T03:35:17.239984Z
addr = 0x1920960
size = 0x3d9
name = "CSource2GameClients_SendHLTVStatusMessage"

[header]
name = "CSource2GameClients_SendHLTVStatusMessage"
addr = 0x1920960

[header.args]
