last_change = 2026-09-10T06:55:51.741421Z
addr = 0x1920960
size = 0x3d9
name = "CSource2GameClients_SendHLTVStatusMessage"

[header]
name = "CSource2GameClients_SendHLTVStatusMessage"
addr = 0x1920960

[header.args]
