last_change = 2026-09-11T03:35:17.240010Z
addr = 0x1963a70
size = 0x6e
name = "CMultiplayRules_ClientDisconnected"

[header]
name = "CMultiplayRules_ClientDisconnected"
addr = 0x1963a70

[header.args]
