last_change = 2026-09-10T18:39:27.423941Z
addr = 0x198f820
size = 0xd7
name = "CBaseEntity_VPhysicsStartTouch"
type = "long long"

[header]
name = "CBaseEntity_VPhysicsStartTouch"
addr = 0x198f820
type = "long long"

[header.args]
