last_change = 2026-09-10T18:39:02.342328Z
addr = 0x19d3ac0
size = 0x1a6
name = "CPlayerCommandQueue_ctor"
type = "long long"

[header]
name = "CPlayerCommandQueue_ctor"
addr = 0x19d3ac0
type = "long long"

[header.args]
