last_change = 2026-09-10T18:39:02.342353Z
addr = 0x1a916e0
size = 0x104e
name = "GetCSceneEntityScriptDesc"
type = "long long"

[header]
name = "GetCSceneEntityScriptDesc"
addr = 0x1a916e0
type = "long long"

[header.args]
