last_change = 2026-09-11T03:35:42.846428Z
addr = 0x1ac2c30
size = 0x3d
name = "CTriggerGravity_GetTouchFunction"
type = "long long"

[header]
name = "CTriggerGravity_GetTouchFunction"
addr = 0x1ac2c30
type = "long long"

[header.args]
