last_change = 2026-09-11T03:35:17.240163Z
addr = 0x2072ce0
size = 0x43
name = "CLoopModeRegistry_UnregisterLoopModes"

[header]
name = "CLoopModeRegistry_UnregisterLoopModes"
addr = 0x2072ce0

[header.args]
