last_change = 2026-09-10T18:39:28.311077Z
addr = 0x2072ce0
size = 0x43
name = "CLoopModeRegistry_UnregisterLoopModes"
type = "long long"

[header]
name = "CLoopModeRegistry_UnregisterLoopModes"
addr = 0x2072ce0
type = "long long"

[header.args]
