last_change = 2026-09-11T03:35:17.240207Z
addr = 0x213e0f0
size = 0x90
name = "CEntityInstance_ValidatePrivateScriptScope"

[header]
name = "CEntityInstance_ValidatePrivateScriptScope"
addr = 0x213e0f0

[header.args]
