last_change = 2026-09-11T03:35:17.240202Z
addr = 0x213db80
size = 0x22
name = "CEntityInstance_PostDataUpdateDelta"

[header]
name = "CEntityInstance_PostDataUpdateDelta"
addr = 0x213db80

[header.args]
