last_change = 2026-09-10T18:39:02.342441Z
addr = 0x213db80
size = 0x22
name = "CEntityInstance_PostDataUpdateDelta"
type = "long long (*)(void)"

[header]
name = "CEntityInstance_PostDataUpdateDelta"
addr = 0x213db80
type = "long long (*)(void)"

[header.args]
