last_change = 2026-09-10T18:39:02.342549Z
addr = 0x214aed0
size = 0x4dd
name = "CConcreteEntityList_FreeEntity"
type = "unsigned long long"

[header]
name = "CConcreteEntityList_FreeEntity"
addr = 0x214aed0
type = "unsigned long long"

[header.args]
