last_change = 2026-09-11T03:35:17.240316Z
addr = 0x214c630
size = 0xad
name = "CEntitySystem_AddEntityToEntityDataBase"

[header]
name = "CEntitySystem_AddEntityToEntityDataBase"
addr = 0x214c630

[header.args]
