last_change = 2026-09-11T03:35:17.240325Z
addr = 0x214efe0
size = 0x32f
name = "CEntitySystem_ExecuteQueuedPostDataUpdateAndActivates"

[header]
name = "CEntitySystem_ExecuteQueuedPostDataUpdateAndActivates"
addr = 0x214efe0

[header.args]
