last_change = 2026-09-10T18:39:29.562160Z
addr = 0x214fd10
size = 0x25
name = "CEntitySystem_RegisterAccessor"
type = "void"

[header]
name = "CEntitySystem_RegisterAccessor"
addr = 0x214fd10
type = "void"

[header.args]
