last_change = 2026-09-11T03:35:17.240330Z
addr = 0x214fcf0
size = 0x20
name = "CEntityKeyValuesAllocator_GetTempBuffer"

[header]
name = "CEntityKeyValuesAllocator_GetTempBuffer"
addr = 0x214fcf0

[header.args]
