last_change = 2026-09-11T03:35:17.240252Z
addr = 0x2146990
size = 0x1
name = "CEntitySystem_OnEntityParentChanged"

[header]
name = "CEntitySystem_OnEntityParentChanged"
addr = 0x2146990

[header.args]
