last_change = 2026-09-11T03:35:17.240434Z
addr = 0x215c0a0
size = 0x28d
name = "CEntitySystem_DestroyEntityImmediate"

[header]
name = "CEntitySystem_DestroyEntityImmediate"
addr = 0x215c0a0

[header.args]
