last_change = 2026-09-11T03:35:17.240380Z
addr = 0x2155530
size = 0x41
name = "CEntitySystem_ForceSetInPVSCallsIntoQueue"

[header]
name = "CEntitySystem_ForceSetInPVSCallsIntoQueue"
addr = 0x2155530

[header.args]
