last_change = 2026-09-11T03:35:17.240351Z
addr = 0x2150660
size = 0x22a
name = "CEntitySystem_AddEntityIOEventBuildStruct"

[header]
name = "CEntitySystem_AddEntityIOEventBuildStruct"
addr = 0x2150660

[header.args]
