last_change = 2026-09-11T03:35:17.240404Z
addr = 0x2159280
size = 0x186
name = "CEntitySystem_ProcessEntityRegistration"

[header]
name = "CEntitySystem_ProcessEntityRegistration"
addr = 0x2159280

[header.args]
