last_change = 2026-09-10T06:55:51.741582Z
addr = 0x2159280
size = 0x186
name = "CEntitySystem_ProcessEntityRegistration"

[header]
name = "CEntitySystem_ProcessEntityRegistration"
addr = 0x2159280

[header.args]
