last_change = 2026-09-10T06:55:51.741567Z
addr = 0x2152ec0
size = 0x678
name = "CEntitySystem_HelperExecuteQueuedSpawn"

[header]
name = "CEntitySystem_HelperExecuteQueuedSpawn"
addr = 0x2152ec0

[header.args]
