last_change = 2026-09-11T03:35:17.240448Z
addr = 0x215db80
size = 0x24a
name = "CEntitySystem_RegisterEntityClass"

[header]
name = "CEntitySystem_RegisterEntityClass"
addr = 0x215db80

[header.args]
