last_change = 2026-09-11T03:35:17.240492Z
addr = 0x2169f80
size = 0x10
name = "CEntitySystem_PostCreateEntitySystem"

[header]
name = "CEntitySystem_PostCreateEntitySystem"
addr = 0x2169f80

[header.args]
