last_change = 2026-09-11T03:35:17.240511Z
addr = 0x216a870
size = 0xd3
name = "EntityInstanceAssignChangeAccessorPathIds"

[header]
name = "EntityInstanceAssignChangeAccessorPathIds"
addr = 0x216a870

[header.args]
