last_change = 2026-09-11T03:35:45.701123Z
addr = 0x216c620
size = 0x4d2
name = "CEntityIOOutput_FireOutputInternal"

[header]
name = "CEntityIOOutput_FireOutputInternal"
addr = 0x216c620

[header.args]
