last_change = 2026-09-11T03:35:17.240532Z
addr = 0x216aa30
size = 0x26
name = "CEntityInstance_NetworkUpdateState_thunk"

[header]
name = "CEntityInstance_NetworkUpdateState_thunk"
addr = 0x216aa30

[header.args]
