last_change = 2026-09-11T03:35:17.240506Z
addr = 0x216a6d0
size = 0x16e
name = "CNetworkSerializerBindingBuildFilter_GetFieldPriority"

[header]
name = "CNetworkSerializerBindingBuildFilter_GetFieldPriority"
addr = 0x216a6d0

[header.args]
