last_change = 2026-09-10T06:55:51.741621Z
addr = 0x216a6d0
size = 0x16e
name = "CNetworkSerializerBindingBuildFilter_GetFieldPriority"

[header]
name = "CNetworkSerializerBindingBuildFilter_GetFieldPriority"
addr = 0x216a6d0

[header.args]
