last_change = 2026-09-10T06:55:51.741623Z
addr = 0x216a870
size = 0xd3
name = "EntityInstanceAssignChangeAccessorPathIds"

[header]
name = "EntityInstanceAssignChangeAccessorPathIds"
addr = 0x216a870

[header.args]
