last_change = 2026-09-10T18:39:02.342745Z
addr = 0x222a180
size = 0x3739
name = "CNavMesh_GetNearestNavArea"
type = "unsigned long long"

[header]
name = "CNavMesh_GetNearestNavArea"
addr = 0x222a180
type = "unsigned long long"

[header.args]
